services:
  mariadb:
    container_name: mariadb-advanced
    image: mariadb:10.10.2
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - MYSQL_USER=burrowuser
      - MYSQL_PASSWORD=burrowpass123
      - MYSQL_ROOT_PASSWORD=rootpass123
      - MYSQL_DATABASE=burrowdb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass123"]
      timeout: 20s
      retries: 10
    networks:
      - burrow_network

  rabbitmq:
    container_name: rabbitmq-advanced
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=burrowuser
      - RABBITMQ_DEFAULT_PASS=burrowpass123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 30s
      retries: 10
    networks:
      - burrow_network

  app-advanced:
    container_name: burrowctl-server-validation
    build:
      context: ../../../..
      dockerfile: examples/server/Dockerfile
      args:
        EXAMPLE_DIR: advanced/validation-server
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - TZ=America/Argentina/Buenos_Aires
      # Advanced server configuration via environment variables
      - BURROWCTL_WORKERS=20
      - BURROWCTL_QUEUE_SIZE=500
      - BURROWCTL_RATE_LIMIT=50
      - BURROWCTL_BURST_SIZE=100
      - BURROWCTL_POOL_IDLE=20
      - BURROWCTL_POOL_OPEN=50
      - BURROWCTL_DEVICE_ID=fd1825ec5a7b63f3fa2be9e04154d3b16f676663ba38e23d4ffafa7b0df29efb
      - BURROWCTL_AMQP_URL=amqp://burrowuser:burrowpass123@rabbitmq-advanced:5672/
      - BURROWCTL_MYSQL_DSN=burrowuser:burrowpass123@tcp(mariadb-advanced:3306)/burrowdb?parseTime=true
    networks:
      - burrow_network
    # Override the default command to use advanced server with optimized settings
    command: [
      "/app/server", 
      "-workers=20", 
      "-queue-size=500", 
      "-rate-limit=50", 
      "-burst-size=100", 
      "-pool-idle=20", 
      "-pool-open=50", 
      "-device=fd1825ec5a7b63f3fa2be9e04154d3b16f676663ba38e23d4ffafa7b0df29efb",
      "-amqp=amqp://burrowuser:burrowpass123@rabbitmq-advanced:5672/", 
      "-mysql=burrowuser:burrowpass123@tcp(mariadb-advanced:3306)/burrowdb?parseTime=true"
    ]

volumes:
  mariadb_data:
  rabbitmq_data:

networks:
  burrow_network:
    driver: bridge